
filebeat.prospectors:

- input_type: log

  paths:
    - C:/Users/diego.cairone/git/odataexample-olingo/odataexample/target/odataexample-app.log
  fields:
    appName: ODATAEXAMPLE_OLINGO
    customer: EIV_SOFTWARE-EQ016
 
  multiline:
    pattern: '^\[%{TIMESTAMP_ISO8601:TIMESTAMP}\]'
    negate: true
  #The after setting is equivalent to previous in Logstash
    match: after

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["localhost:5044"]
